naxsi:
  image: scollazo/naxsi-waf-with-ui:latest
  ports:
    - "80:80"
    - "8080:8080"
  environment:
    BACKEND_IP: "93.184.216.34"
    LEARNING_MODE: "yes"
    # KIBANA_PASSWORD: "your-supersecret-password"
  links:
    - elasticsearch
    - kibana
  volumes:
    - ./nginx/naxsi-local-rules:/etc/nginx/naxsi-local-rules

elasticsearch:
  image: elasticsearch:7.11.1
  command: elasticsearch -Enetwork.host=0.0.0.0
# Uncomment to allow access from network
#  ports:
#    - "9200:9200"
#    - "9300:9300"
  volumes:
    - ./elasticsearch-data:/usr/share/elasticsearch/data

kibana:
  image: kibana:7.11.1
  command: gosu kibana kibana
  volumes:
    - ./kibana/kibana.yml:/opt/kibana/config/kibana.yml
  links:
    - elasticsearch

